export const practiceTests = [
  {
    id: 'math-basics',
    title: 'Math Basics (MCQ)',
    category: 'Mathematics',
    duration: 10,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'What is 7 + 5?',
        options: ['10', '11', '12', '13'],
        answerIndex: 2,
      },
      {
        id: 'q2',
        text: 'What is 9 - 4?',
        options: ['3', '4', '5', '6'],
        answerIndex: 2,
      },
      {
        id: 'q3',
        text: 'What is 6 × 3?',
        options: ['9', '18', '12', '21'],
        answerIndex: 1,
      },
      {
        id: 'q4',
        text: 'What is 20 ÷ 5?',
        options: ['2', '4', '5', '10'],
        answerIndex: 2,
      },
      {
        id: 'q5',
        text: 'What is 15 - 9?',
        options: ['4', '6', '7', '8'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'english-grammar',
    title: 'English Grammar (MCQ)',
    category: 'English',
    duration: 10,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Choose the correct sentence.',
        options: ['He don\'t like tea.', 'He doesn\'t like tea.', 'He not like tea.', 'He no like tea.'],
        answerIndex: 1,
      },
      {
        id: 'q2',
        text: 'Select the synonym of "happy".',
        options: ['sad', 'joyful', 'angry', 'tired'],
        answerIndex: 1,
      },
      {
        id: 'q3',
        text: 'Fill in the blank: She ____ to school every day.',
        options: ['go', 'goes', 'going', 'gone'],
        answerIndex: 1,
      },
      {
        id: 'q4',
        text: 'Choose the correct article: I saw ____ elephant.',
        options: ['a', 'an', 'the', 'no article'],
        answerIndex: 1,
      },
      {
        id: 'q5',
        text: 'Choose the antonym of "difficult".',
        options: ['hard', 'easy', 'tough', 'rough'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'js-basics',
    title: 'JavaScript Basics (MCQ)',
    category: 'Programming',
    duration: 12,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which of the following is NOT a primitive type in JavaScript?',
        options: ['string', 'number', 'boolean', 'object'],
        answerIndex: 3,
      },
      {
        id: 'q2',
        text: 'What is the output of typeof null?',
        options: ['null', 'object', 'undefined', 'boolean'],
        answerIndex: 1,
      },
      {
        id: 'q3',
        text: 'Which method converts a JSON string to an object?',
        options: ['JSON.parse()', 'JSON.stringify()', 'Object.parse()', 'toObject()'],
        answerIndex: 0,
      },
      {
        id: 'q4',
        text: 'Which symbol is used to declare a template literal?',
        options: ['"', "'", '`', '~'],
        answerIndex: 2,
      },
      {
        id: 'q5',
        text: 'Which array method creates a new array with the results of calling a function on every element?',
        options: ['forEach', 'map', 'filter', 'reduce'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'react-basics',
    title: 'React Basics (MCQ)',
    category: 'Frontend',
    duration: 12,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which hook is used for managing component state?',
        options: ['useEffect', 'useState', 'useMemo', 'useRef'],
        answerIndex: 1,
      },
      {
        id: 'q2',
        text: 'What is the correct way to pass props in JSX?',
        options: ['<Comp props={data} />', '<Comp data />', '<Comp data={value} />', '<Comp {data} />'],
        answerIndex: 2,
      },
      {
        id: 'q3',
        text: 'Keys in lists help React identify which items have changed. What should be used as keys?',
        options: ['Index always', 'Random values', 'Stable unique IDs', 'Component names'],
        answerIndex: 2,
      },
      {
        id: 'q4',
        text: 'Which hook runs after render and can perform side effects?',
        options: ['useEffect', 'useState', 'useCallback', 'useLayout'],
        answerIndex: 0,
      },
      {
        id: 'q5',
        text: 'In React Router, which component is used to navigate programmatically?',
        options: ['Link', 'NavLink', 'useNavigate', 'Route'],
        answerIndex: 2,
      },
    ],
  },
  {
    id: 'data-structures',
    title: 'Data Structures (MCQ)',
    category: 'Computer Science',
    duration: 15,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which data structure uses FIFO?',
        options: ['Stack', 'Queue', 'Tree', 'Graph'],
        answerIndex: 1,
      },
      {
        id: 'q2',
        text: 'What is the time complexity of accessing an element by index in an array?',
        options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'],
        answerIndex: 0,
      },
      {
        id: 'q3',
        text: 'Which traversal of a binary search tree yields a sorted sequence?',
        options: ['Preorder', 'Postorder', 'Inorder', 'Level order'],
        answerIndex: 2,
      },
      {
        id: 'q4',
        text: 'A hash table resolves collisions commonly using:',
        options: ['Binary search', 'Chaining', 'Quick sort', 'DFS'],
        answerIndex: 1,
      },
      {
        id: 'q5',
        text: 'Which structure is best for implementing recursion?',
        options: ['Queue', 'Stack', 'Heap', 'Deque'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'algorithms',
    title: 'Algorithms (MCQ)',
    category: 'Computer Science',
    duration: 15,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which algorithm is used for finding the shortest path in a weighted graph with non-negative weights?',
        options: ['DFS', 'BFS', "Dijkstra's", 'Kruskal'],
        answerIndex: 2,
      },
      {
        id: 'q2',
        text: 'Average time complexity of quicksort is:',
        options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'],
        answerIndex: 1,
      },
      {
        id: 'q3',
        text: 'Which algorithm is used for minimum spanning tree?',
        options: ['Prim/Kruskal', 'Dijkstra', 'Bellman-Ford', 'Floyd–Warshall'],
        answerIndex: 0,
      },
      {
        id: 'q4',
        text: 'Which technique is used to reduce overlapping subproblems?',
        options: ['Greedy', 'Divide and Conquer', 'Dynamic Programming', 'Backtracking'],
        answerIndex: 2,
      },
      {
        id: 'q5',
        text: 'Binary search requires the input to be:',
        options: ['Random', 'Sorted', 'Unique', 'Balanced'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'sql-fundamentals',
    title: 'SQL Fundamentals (MCQ)',
    category: 'Databases',
    duration: 12,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which SQL clause is used to filter rows?',
        options: ['ORDER BY', 'WHERE', 'GROUP BY', 'JOIN'],
        answerIndex: 1,
      },
      {
        id: 'q2',
        text: 'Which SQL statement adds a new row?',
        options: ['INSERT', 'UPDATE', 'ALTER', 'CREATE'],
        answerIndex: 0,
      },
      {
        id: 'q3',
        text: 'Which join returns only matching rows from both tables?',
        options: ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'],
        answerIndex: 2,
      },
      {
        id: 'q4',
        text: 'What does COUNT(*) count?',
        options: ['Only non-null', 'Only numeric', 'All rows', 'Distinct rows'],
        answerIndex: 2,
      },
      {
        id: 'q5',
        text: 'Which keyword removes duplicate rows in a SELECT?',
        options: ['UNIQUE', 'DISTINCT', 'ONLY', 'FILTER'],
        answerIndex: 1,
      },
    ],
  },
  {
    id: 'networking-basics',
    title: 'Networking Basics (MCQ)',
    category: 'Networking',
    duration: 10,
    totalQuestions: 5,
    questions: [
      {
        id: 'q1',
        text: 'Which protocol is used for secure HTTP?',
        options: ['FTP', 'HTTP', 'HTTPS', 'SMTP'],
        answerIndex: 2,
      },
      {
        id: 'q2',
        text: 'What is the default port of HTTP?',
        options: ['80', '443', '21', '25'],
        answerIndex: 0,
      },
      {
        id: 'q3',
        text: 'Which device operates at Layer 3 of the OSI model?',
        options: ['Switch', 'Router', 'Hub', 'Bridge'],
        answerIndex: 1,
      },
      {
        id: 'q4',
        text: 'DNS resolves:',
        options: ['IP to MAC', 'Domain to IP', 'MAC to IP', 'IP to Domain'],
        answerIndex: 1,
      },
      {
        id: 'q5',
        text: 'Which protocol is connection-oriented?',
        options: ['UDP', 'TCP', 'ICMP', 'ARP'],
        answerIndex: 1,
      },
    ],
  },
];
